### ISSUE TITLE
Text wrap in Course card

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#10]
## Expected Behavior

Text should be wrapped in the Card.
![image](https://user-images.githubusercontent.com/13796098/155531275-d8820974-cb87-4860-82e5-ccafd520b8f9.png)

## Current Behavior

The description of projects is not wrapped in the card.
![image](https://user-images.githubusercontent.com/13796098/155531211-560c559c-3991-44b6-986b-e9d0f1f0d7fa.png)

**Comment by Salik-Rafiq** [comment]
Ready for review.

**Comment by BbrSofiane** [comment]
Fixed
