### ISSUE TITLE
Update tab description information

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#11]
## Expected Behavior

Text displayed in the browser tab description should be set to customised to the specific MFE (see example for the classroom MFE).
![image](https://user-images.githubusercontent.com/13796098/155531798-fbf9380d-7759-48f6-ad43-1bbe2dd1a0c9.png)

## Current Behavior

The tab descriptions has the default placeholder of the template.
![image](https://user-images.githubusercontent.com/13796098/155531639-a0fd294a-5ad3-497c-a855-5cce8c04d454.png)

## Possible Solution

Update index.html with the correct description.

**Comment by Salik-Rafiq** [comment]
You mean Dashboard?  The classroom plugin should show Classroom.

**Comment by Salik-Rafiq** [comment]
Ready for review

**Comment by BbrSofiane** [comment]
Fixed
