### ISSUE TITLE
Courses should be in order of the most recent to the oldest

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#12]
Courses displayed in the dashboard should be sorted in chronological order.

## Expected Behavior

The legacy dashboard displays courses in from the most recent course the user is enrolled in, to the oldest. The order should be the same in the MFE dashboard.

![image](https://user-images.githubusercontent.com/13796098/155694738-0ab1e271-d4d3-4b6c-b6e7-8ca4278c06f9.png)

## Current Behavior

It looks like the courses are in the reverse order, i.e., oldest course enrolled in first.

![image](https://user-images.githubusercontent.com/13796098/155694590-86f300a6-680d-4ccd-8099-38124fa95c8d.png)

**Comment by BbrSofiane** [comment]
Same for classrooms.

**Comment by Salik-Rafiq** [comment]
When you say "same for classrooms" you mean the classrooms list in the dashboard yes?

**Comment by BbrSofiane** [comment]
Yes, the classroom list in the dashboard should be sorted from most recent to oldest.

**Comment by Salik-Rafiq** [comment]
On the classrooms. The data I get back from the API doesn't have a date. Perhaps internally there is a created date which can be exposed on the /v1/classrooms API.

I've done the other part of it.

**Comment by BbrSofiane** [comment]
Ahh indeed... ok that's on me I'll send the creation timestamp of the classroom.

**Comment by BbrSofiane** [comment]
Looks good to me!

For the classroom, I will return the data in the correct order. I've created a separate issue for it.

See Dicey-Tech/dt-backend-services#20
