### ISSUE TITLE
Hide "Find new courses" on the learner dashboard

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#13]
## Current Behavior

On the learners' dashboard, we have a card "Find new courses" that currently doesn't have a use. 

![image](https://user-images.githubusercontent.com/13796098/157434963-757b6669-8c8d-47bb-a0a3-a9affa0a7712.png)

## Possible Solution

Can we make the visibility of the card conditional? For example, the card should only be displayed if a configuration variable is set (e.g. `DISCOVER_CONTENT_URL`). That way when we have a clear idea of how we want the user experience of discovering new content looks like, we don't have to write additional code.

**Comment by Salik-Rafiq** [comment]
Can do. A config can be created for this and the display of that can be based on this.

I will have to look at the layout html and adjust as appropriate. Hopefully it's simple.

**Comment by Salik-Rafiq** [comment]
We already have a `EXPLORE_COURSES_URL` which I can blank/null out and if it is null than the explore card won't be visible.

**Comment by BbrSofiane** [comment]
Tested and it works!
