### ISSUE TITLE
"Currently Teaching" course cards don't allow navigation to courses

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#14]
## Expected Behavior

A educator should be able to navigate to a course from the "Currently teaching" row,

## Current Behavior

Educators can only navigate to the gradebook.

**Comment by Salik-Rafiq** [comment]
Do you want a button or click on the card.  Most other places have a button.

**Comment by BbrSofiane** [comment]
Would a button make the card wider?

**Comment by Salik-Rafiq** [comment]
Should not do. I will give it a go and let's see.

**Comment by BbrSofiane** [comment]
Looks good to me!
