### ISSUE TITLE
Add Classes Row

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#2]
## Expected Behavior

![image](https://user-images.githubusercontent.com/13796098/141436994-6d159b27-4827-4cc7-acf1-db66db729edf.png)

**Comment by BbrSofiane** [comment]
[Figma](https://www.figma.com/proto/nj9XpgMFZutASCldiGbKXE/Learning-Platform?node-id=322%3A491&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=322%3A491)

**Comment by Salik-Rafiq** [comment]
This is same as the manage page but just nicer looking.   If the classes are a lot I could try some type of carousel rather than a scroll bar?

The New Class - is using the same New Classroom popup as in the  classroom manage - and then it navigates to the class once it's created.

**Comment by BbrSofiane** [comment]
> If the classes are a lot I could try some type of carousel rather than a scroll bar?

I would stick to scroll for now and wait for feedback. If we switch to a carousel we would also need to do that on the wireframes.

**Comment by Salik-Rafiq** [comment]
Will do.

**Comment by Salik-Rafiq** [comment]
I've got the My Classes loading now.  Some CSS tweaks will be needed I think.

The New Class Card  sizes fine with the other when there is no scroll bar - but when there is a scroll bar than it looks a little bigger. I'm not sure how to get around that.

Next up to wire the Add Course card and also to hide it when a user can't add classes.
![Screenshot 2021-11-21 185227](https://user-images.githubusercontent.com/15679538/142775777-a345b77a-94f5-4f53-90f6-c0aa1ce4498f.png)

The images is a sample image. Which one should I use. The one in figma or will another one be made?

**Comment by BbrSofiane** [comment]
Good point about the image. We can use a smaller version of the background image of the classroom. Can you give me a size that will come out nicely? I'll send it over tomorrow.

**Comment by Salik-Rafiq** [comment]
I tried looking at the figma but could not make sense of the image dimensions. But It looks like width 316px. I suppose the height will than be proportional.  I can try copying the svg from classroom and try?

**Comment by BbrSofiane** [comment]
Ok, try it and let me know if it works,

**Comment by Salik-Rafiq** [comment]
OK. copied the SVG over and set the Card dimension to same as figma - 316px(w) X 370px(h) and this is what I got. 

![Screenshot 2021-11-22 201813](https://user-images.githubusercontent.com/15679538/142929348-8075838d-a429-4e89-9650-9bbd0ccb1223.png)

The SVG will need to be updated so its about 316px(w) X ~185px(h) . about that anyway it should look OK.

Though not sure what to do about the blank space there. There still be a lot even with a larger image.

**Comment by Salik-Rafiq** [comment]
OK. pushed up to GitHub just now. Ready for review.

A few glitches there which I will tidy up along with the next section.
