### ISSUE TITLE
Add Currently Teaching Row

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#3]
## Expected Behavior

Add a row to list active courses where the user (teacher) is enrolled as Staff.

![image](https://user-images.githubusercontent.com/13796098/141437523-0e86ee34-50ae-4a7c-b953-865343137040.png)

[Figma](https://www.figma.com/proto/nj9XpgMFZutASCldiGbKXE/Learning-Platform?node-id=322%3A491&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=322%3A491)

**Comment by Salik-Rafiq** [comment]
I think the early stage prototype I did has this in there. so just need to copy that over.

**Comment by Salik-Rafiq** [comment]
Which API should I use for this.

There is the Discovery API and the LMS API. 

The LMS is easy and getting the course where the user is listed as Staff.  But I can't get the enrollment count from that API..I tried with a teacher account and got permission denied. I think this is standard - that user is not an admin.

The Discovery API doesn't seem to limit by role - the 'staff' field is blank and enrollment counts are 0 for everything. Guess I won't use that one!

So. I think, initially won't be able to put enrollment counts on the cards.
