### ISSUE TITLE
Course card layout for courses with no images

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#4]
## Expected Behavior

Course cards should be aligned whether the course has an image of not.

## Current Behavior

![image](https://user-images.githubusercontent.com/13796098/145722986-d0c6986c-653a-4db4-9cad-1fa4e8b97d83.png)

## Possible Solution

Use a generic image for courses with no images

**Comment by Salik-Rafiq** [comment]
When a course has no image it looks like the LMS is filling in this by supplying a uri to an image called "pencils.jpg".
So, on the client side - not much we can do really other than look at the CSS and see how to prevent that issue by using CSS?

the uri I'm getting in this case is http://local.overhang.io:8000/static/studio/images/pencils.jpg

Which is giving me a 404.

**Comment by Salik-Rafiq** [comment]
ah! I can use the onError to replace the image. So I've done that. Update coming.
