### ISSUE TITLE
Scroll bar appearance

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#5]
## Expected Behavior

The scroll bar should be styled in line with the page branding. (@BbrSofiane need to update it on Figma).
* The bar colour should be the primary colour.
* Round the edge of the bar

## Current Behavior

![image](https://user-images.githubusercontent.com/13796098/145723148-837cfd30-8b95-4360-b107-bcf07d5e362c.png)

**Comment by Salik-Rafiq** [comment]
You want this for both horizontal under the cards and the vertical as well? Can be done I believe looking at the CSS.

Though the CSS is experimental looking at what I've seen. One set for webkit (Chrome, Edge) and another for FireFox.

**Comment by BbrSofiane** [comment]
I've tried it and it looks good. Let's close Dicey-Tech/brand-diceytech#3 before we close this one.
