### ISSUE TITLE
Improve spacing

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#6]
## Expected Behavior

![image](https://user-images.githubusercontent.com/13796098/145724853-f83fc4a0-1bc8-488f-9f52-98cceb830a84.png)

[Figma](https://www.figma.com/proto/nj9XpgMFZutASCldiGbKXE/Learning-Platform?node-id=322%3A491&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=322%3A491&show-proto-sidebar=1)

## Current Behavior

![image](https://user-images.githubusercontent.com/13796098/145724879-a4fbe61d-9550-46d6-aaef-23f186251461.png)

**Comment by BbrSofiane** [comment]
Is it just me or would it be better to add some spacing between the footer and the bottom of the "Currently teaching" row?

![image](https://user-images.githubusercontent.com/13796098/145989405-e8424bf3-aec5-4c3a-9671-d07919ad0cbd.png)

**Comment by Salik-Rafiq** [comment]
Ah! yeah could use some padding in places. I'll look into what bootstrap styles there are.

**Comment by Salik-Rafiq** [comment]
Made a couple of small changes to the CSS.

A bit of padding above the scrollbar so the cards arn't flush against the scrollbar. 
Margin after the last section of cards.
