### ISSUE TITLE
Combine teacher and student dashboard

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#7]
## Expected Behavior

Depending on a user's role in an enterprise, display the appropriate components.

### Teachers
- Classroom row
- Currently teaching courses

![image](https://user-images.githubusercontent.com/13796098/145810454-d9697520-dfd0-4fc3-bbfa-0453f74ec46b.png)

### Students
- Currently enrolled courses

![image](https://user-images.githubusercontent.com/13796098/145810413-b77d9aae-67b6-465a-8630-18c1a886123d.png)

**Comment by Salik-Rafiq** [comment]
Is there a spec for telling the difference between a student & teacher. I'm also wondering if a person can be both?

**Comment by Salik-Rafiq** [comment]
Looks like a student is a person where:

administrator: false
roles: []

So no roles at all?

But a teacher roles can be: [enterprise_learner:<uuid>,enterprise_admin:<uuid>]

I'm wondering if just having 'enterprise_learner' is also a student?

**Comment by BbrSofiane** [comment]
For now, you can assume anyone that doesn't have enterprise_admin is a student. That way it covers the case where the user is not linked to an enterprise.

**Comment by Salik-Rafiq** [comment]
OK. First go at this. is in!
