### ISSUE TITLE
Currently Teaching returns all courses not just the ones where user role is staff

### ISSUE THREAD

**Issue by Salik-Rafiq** [Dicey-Tech/frontend-app-dashboard#8]
## Expected Behavior
The Currently Teaching section should only return courses the current user is teaching - ie: where their role is 'staff'

## Current Behavior

It's returning all the courses visible to user regardless if they are teaching it or not.

## Possible Solution

It's using the wrong API. Should use /api/courses/v1/course_ids which accepts a 'role of staff and REQUIRES the username parameter to work . Note that the swagger docs say it's optional but it will most likely error if you don't put a username.

## Steps to Reproduce (for bugs)

1. Sign in to platform with a teacher account
2. enter in apps.local.overhang.io:1999  - to get to the teacher dashboard
3. notice the large number of courses in the Currently Teaching section
4. Compare these to the course you are actually teaching - there will be a difference.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Salik-Rafiq** [comment]
Update the code to the correct API call.   for admin@example.com and staff@example.com seem to get the same list of "teaching" courses. And my admins in each of enterprises don't seem to be teaching any - though they have classrooms with courses in them.... Perhaps something is out of sync?

**Comment by Salik-Rafiq** [comment]
This needs to double checked that it's working properly. @BbrSofiane  can you check it?

**Comment by BbrSofiane** [comment]
It works for me. When logged in with an enterprise admin user that is enrolled as staff in 1 course and as learner 3 others, only the course I was enrolled in as staff was displayed.
