### ISSUE TITLE
Align "New classroom" pop up with wireframe

### ISSUE THREAD

**Issue by BbrSofiane** [Dicey-Tech/frontend-app-dashboard#9]
## Expected Behavior

![image](https://user-images.githubusercontent.com/13796098/154487923-03354213-14f0-482d-b686-c2590f311f4d.png)

## Current Behavior

![image](https://user-images.githubusercontent.com/13796098/154485789-a6dd775c-5ea6-44a7-8fb7-dfa3d6533f77.png)

## Possible Solution

- [ ] Remove scroll bar
- [ ] Grey out textbox background F8F7F9
- [ ] Align buttons in the middle
- [ ] Remove title

**Comment by Salik-Rafiq** [comment]
OK, In.

**Comment by BbrSofiane** [comment]
Fixed
